// Defines the structure (contract) for an Attendance record
export interface Attendance {
  // Optional unique identifier (UUID generated by the database)
  id?: string;

  // Reference to the employee who this attendance belongs to (foreign key)
  employee_id: string;

  // Time when the employee checked in (nullable if absent or not recorded)
  check_in_time?: Date | null;

  // Time when the employee checked out (nullable if absent or not recorded)
  check_out_time?: Date | null;

  // Attendance status, restricted to specific values:
  // "Hadir" = Present
  // "Izin"  = Permission/Excused absence
  // "Sakit" = Sick
  // "Cuti"  = Leave
  // "Alpha" = Absent without permission
  status: 'Hadir' | 'Izin' | 'Sakit' | 'Cuti' | 'Alpha';

  // Optional notes for additional information (e.g., reason for leave)
  notes?: string | null;

  // The date of attendance (required)
  attendance_date: Date;
}
