// src/interfaces/employee.interface.ts

// Define the structure (contract) for an Employee object
export interface Employee {
  // Optional unique identifier (UUID will be generated by the database)
  id?: string;

  // Full name of the employee (required)
  full_name: string;

  // Employee's email address (required, typically unique)
  email: string;

  // Hashed password of the employee (required, never store plain text)
  password_hash: string;

  // Job title of the employee (optional, can also be null)
  job_title?: string | null;

  // Department where the employee works (optional, can also be null)
  department?: string | null;

  // Employment status, restricted to two possible values
  // "Aktif" = Active, "Tidak Aktif" = Inactive
  employment_status: 'Aktif' | 'Tidak Aktif';

  // Role assigned to the employee
  // "Admin" = system administrator
  // "HR" = human resources staff
  // "Karyawan" = regular employee
  role: 'Admin' | 'HR' | 'Karyawan';

  // Timestamp when the employee record was created (optional)
  created_at?: Date;

  // Timestamp when the employee record was last updated (optional)
  updated_at?: Date;
}
