// Defines the structure (contract) for a Leave Request record
export interface LeaveRequest {
  // Optional unique identifier (UUID generated by the database)
  id?: string;

  // Reference to the employee requesting leave (foreign key)
  employee_id: string;

  // Type of leave (e.g., Sick Leave, Annual Leave, Unpaid Leave, etc.)
  leave_type: string;

  // Start date of the leave (required)
  start_date: Date;

  // End date of the leave (required)
  end_date: Date;

  // Reason provided by the employee for requesting leave
  reason: string;

  // Status of the leave request:
  // "Pending"   = waiting for approval
  // "Disetujui" = approved
  // "Ditolak"   = rejected
  status: 'Pending' | 'Disetujui' | 'Ditolak';

  // The ID of the manager/HR who approved or rejected the request (nullable if still pending)
  approved_by?: string | null;
}
